# Generated by Django 5.1.5 on 2025-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(db_column='Aid', primary_key=True, serialize=False)),
                ('aname', models.CharField(db_column='Aname', max_length=45)),
                ('phone_number', models.BigIntegerField(db_column='Phone-number')),
                ('email_id', models.CharField(blank=True, db_column='Email-id', max_length=45, null=True)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(db_column='cat-id', primary_key=True, serialize=False)),
                ('cat_name', models.CharField(db_column='cat-name', max_length=50)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField(db_column='Phone_number')),
                ('email_id', models.CharField(blank=True, db_column='Email-id', max_length=45, null=True)),
                ('address', models.CharField(db_column='Address', max_length=500)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fed_id', models.AutoField(db_column='Fed-id', primary_key=True, serialize=False)),
                ('descrip', models.CharField(db_column='Descrip', max_length=500)),
                ('fdate', models.DateField(db_column='Fdate')),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fid', models.AutoField(db_column='Fid', primary_key=True, serialize=False)),
                ('f_name', models.CharField(db_column='f-name', max_length=300)),
                ('description', models.CharField(db_column='Description', max_length=2500)),
                ('type', models.CharField(db_column='Type', max_length=45)),
                ('img', models.CharField(db_column='Img', max_length=5000)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('lid', models.AutoField(db_column='Lid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('mid', models.AutoField(db_column='Mid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('off_id', models.AutoField(db_column='off-id', primary_key=True, serialize=False)),
                ('desc', models.CharField(db_column='Desc', max_length=500)),
                ('rate', models.IntegerField()),
                ('fd_id', models.IntegerField(blank=True, db_column='Fd-id', null=True)),
            ],
            options={
                'db_table': 'offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(db_column='Oid', primary_key=True, serialize=False)),
                ('oname', models.CharField(max_length=800)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('amount', models.IntegerField(db_column='Amount')),
                ('customization', models.CharField(blank=True, db_column='Customization', max_length=5000, null=True)),
                ('payment_method', models.CharField(db_column='payment-method', max_length=45)),
                ('booking_date', models.DateField(db_column='Booking-date')),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rep_id', models.AutoField(db_column='Rep-id', primary_key=True, serialize=False)),
                ('rep_date', models.DateField(db_column='rep-date')),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rid', models.AutoField(db_column='Rid', primary_key=True, serialize=False)),
                ('rname', models.CharField(db_column='Rname', max_length=200)),
                ('address', models.CharField(db_column='Address', max_length=500)),
                ('contact_number', models.BigIntegerField(db_column='contact-number')),
                ('email_id', models.CharField(blank=True, db_column='Email-id', max_length=45, null=True)),
                ('registration_number', models.BigIntegerField(db_column='Registration-number')),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sid', models.AutoField(db_column='Sid', primary_key=True, serialize=False)),
                ('royalty_amt', models.IntegerField(blank=True, db_column='Royalty-amt', null=True)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
    ]
