# Generated by Django 5.1.5 on 2025-03-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_admin_delete_category_delete_feedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
