# Generated by Django 5.1.5 on 2025-03-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_order_options'),
        ('restaurant', '0004_alter_restaurant_rest_image'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='order',
            name='res_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurant'),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
