# Generated by Django 5.1.5 on 2025-03-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_cus_id_order_res_id_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cus_id',
            field=models.ForeignKey(blank=True, db_column='cus_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer'),
        ),
    ]
