# Generated by Django 5.1.5 on 2025-03-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='rest_images/'),
        ),
    ]
