# Generated by Django 5.1.5 on 2025-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_rest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='rest_image/'),
        ),
    ]
